version: '3.6'

services:

    lang-db:
        image: postgres
        environment:
          POSTGRES_DB: operationdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            # - ./js.sql:/docker-entrypoint-initdb.d/js.sql
            - ./z-full.sql:/docker-entrypoint-initdb.d/z-full.sql
            # - ./Zplusplus.sql:/docker-entrypoint-initdb.d/Zplusplus.sql
            # - ./ZC#.sql:/docker-entrypoint-initdb.d/ZC#.sql


networks:
  default: {}
