version: '3.6'

services:

    lang-db:
        image: postgres
        environment:
          POSTGRES_DB: operationdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./js.sql:/docker-entrypoint-initdb.d/js.sql
            - ./python.sql:/docker-entrypoint-initdb.d/python.sql
            - ./l_C#.sql:/docker-entrypoint-initdb.d/l_C#.sql


networks:
  default: {}
